name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Yo this issue is kind of getting stale, wanna check on it?'
        stale-pr-message: 'Yoooo something needs to happen to this pull req soon.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
